# Generated by Django 2.2.4 on 2021-01-12 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dojo',
            name='desc',
            field=models.CharField(default='dojo', max_length=255),
            preserve_default=False,
        ),
    ]
