# Generated by Django 2.2.4 on 2021-01-13 00:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_dojo_desc'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dojo',
            name='desc',
        ),
    ]
